spring.application.name=attachement-module
server.port=8082

spring.data.mongodb.database=attachement
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27019

file.upload-image-dir=./src/main/resources/files/images
file.upload-docs-dir=./src/main/resources/files/docs
file.upload-cv-dir=./src/main/resources/files/cvs


eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.config.uri=http://localhost:8888
spring.config.import=optional:configserver:http://localhost:8888