spring.application.name=attachement-module
server.port=8082
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.database=attachement
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27019
spring.data.mongodb.username=admin
spring.data.mongodb.password=admin
file.upload-image-dir=./src/main/resources/files/images
file.upload-docs-dir=./src/main/resources/files/docs
file.upload-cv-dir=./src/main/resources/files/cvs