spring:
  application:
    name:  attachement-service
  data:
    mongodb:
      host: localhost
      port: 27018
      database: attachement

  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8082
candidate:
  service:
    url: http://localhost:8888
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

file:
  upload-image-dir: attachement/src/main/resources/files/images
  upload-docs-dir: attachement/src/main/resources/files/docs
  upload-cv-dir: attachement/src/main/resources/files/cvs