import { Company, Client, Announcement, Stats } from '../types';
import { subDays, format } from 'date-fns';

const formatDate = (daysAgo: number) => format(subDays(new Date(), daysAgo), 'yyyy-MM-dd');

export const mockCompanies: Company[] = [
  {
    id: 'comp-001',
    name: 'Admin',
    email: 'admin@techcorp.com',
    role: 'company',
    status: 'active',
    createdAt: formatDate(230),
    lastLogin: formatDate(2),
    companyName: 'TechCorp Solutions',
    industry: 'Technology',
    size: '50-200',
    logo: 'https://images.pexels.com/photos/5726837/pexels-photo-5726837.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'San Francisco, CA',
    jobsPosted: 15,
    verified: true,
  },
  {
    id: 'comp-002',
    name: 'Admin',
    email: 'admin@globalfinance.com',
    role: 'company',
    status: 'active',
    createdAt: formatDate(180),
    lastLogin: formatDate(5),
    companyName: 'Global Finance Inc.',
    industry: 'Finance',
    size: '500-1000',
    logo: 'https://images.pexels.com/photos/936137/pexels-photo-936137.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'New York, NY',
    jobsPosted: 32,
    verified: true,
  },
  {
    id: 'comp-003',
    name: 'Admin',
    email: 'admin@medicalplus.com',
    role: 'company',
    status: 'pending',
    createdAt: formatDate(10),
    companyName: 'Medical Plus',
    industry: 'Healthcare',
    size: '20-50',
    logo: 'https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'Chicago, IL',
    jobsPosted: 5,
    verified: false,
  },
  {
    id: 'comp-004',
    name: 'Admin',
    email: 'admin@luxdesign.com',
    role: 'company',
    status: 'active',
    createdAt: formatDate(90),
    lastLogin: formatDate(15),
    companyName: 'Lux Design Studio',
    industry: 'Design',
    size: '10-20',
    logo: 'https://images.pexels.com/photos/572056/pexels-photo-572056.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'Los Angeles, CA',
    jobsPosted: 8,
    verified: true,
  },
  {
    id: 'comp-005',
    name: 'Admin',
    email: 'admin@ecofoods.com',
    role: 'company',
    status: 'suspended',
    createdAt: formatDate(150),
    lastLogin: formatDate(45),
    companyName: 'EcoFoods Market',
    industry: 'Retail',
    size: '200-500',
    logo: 'https://images.pexels.com/photos/1008155/pexels-photo-1008155.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: 'Portland, OR',
    jobsPosted: 12,
    verified: true,
  },
];

export const mockClients: Client[] = [
  {
    id: 'client-001',
    name: 'John Smith',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@example.com',
    role: 'client',
    status: 'active',
    createdAt: formatDate(120),
    lastLogin: formatDate(1),
    skills: ['JavaScript', 'React', 'Node.js'],
    jobsApplied: 24,
    profileCompleteness: 95,
  },
  {
    id: 'client-002',
    name: 'Sarah Johnson',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@example.com',
    role: 'client',
    status: 'active',
    createdAt: formatDate(90),
    lastLogin: formatDate(3),
    skills: ['UX Design', 'Figma', 'Adobe XD'],
    jobsApplied: 12,
    profileCompleteness: 85,
  },
  {
    id: 'client-003',
    name: 'Miguel Rodriguez',
    firstName: 'Miguel',
    lastName: 'Rodriguez',
    email: 'miguel.r@example.com',
    role: 'client',
    status: 'pending',
    createdAt: formatDate(5),
    skills: ['Python', 'Data Analysis', 'SQL'],
    jobsApplied: 0,
    profileCompleteness: 60,
  },
  {
    id: 'client-004',
    name: 'Aisha Patel',
    firstName: 'Aisha',
    lastName: 'Patel',
    email: 'aisha.p@example.com',
    role: 'client',
    status: 'active',
    createdAt: formatDate(180),
    lastLogin: formatDate(7),
    skills: ['Project Management', 'Agile', 'Leadership'],
    jobsApplied: 31,
    profileCompleteness: 100,
  },
  {
    id: 'client-005',
    name: 'Thomas Wilson',
    firstName: 'Thomas',
    lastName: 'Wilson',
    email: 'thomas.w@example.com',
    role: 'client',
    status: 'suspended',
    createdAt: formatDate(200),
    lastLogin: formatDate(60),
    skills: ['Marketing', 'SEO', 'Content Writing'],
    jobsApplied: 18,
    profileCompleteness: 75,
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-001',
    title: 'New Job Posting Guidelines',
    content: 'We are updating our job posting guidelines to ensure better quality and relevance for job seekers. The new guidelines will be effective from next month.',
    source: 'company',
    sourceId: 'comp-001',
    sourceName: 'TechCorp Solutions',
    status: 'published',
    createdAt: formatDate(15),
    expiresAt: formatDate(-15),
  },
  {
    id: 'ann-002',
    title: 'Virtual Career Fair Announcement',
    content: 'We are excited to announce a virtual career fair featuring top companies in the finance industry. Register now to reserve your spot.',
    source: 'company',
    sourceId: 'comp-002',
    sourceName: 'Global Finance Inc.',
    status: 'published',
    createdAt: formatDate(10),
    expiresAt: formatDate(-20),
  },
  {
    id: 'ann-003',
    title: 'Seeking feedback on new resume templates',
    content: 'We have added new resume templates to our platform and would love to get feedback from job seekers about their effectiveness.',
    source: 'client',
    sourceId: 'client-001',
    sourceName: 'John Smith',
    status: 'pending',
    createdAt: formatDate(2),
  },
  {
    id: 'ann-004',
    title: 'Technical Writer Positions Available',
    content: 'We are looking for experienced technical writers to join our growing team. Remote positions available.',
    source: 'company',
    sourceId: 'comp-004',
    sourceName: 'Lux Design Studio',
    status: 'pending',
    createdAt: formatDate(1),
  },
  {
    id: 'ann-005',
    title: 'Networking Event for Healthcare Professionals',
    content: 'Join us for a networking event specifically for healthcare professionals looking to advance their careers.',
    source: 'client',
    sourceId: 'client-004',
    sourceName: 'Aisha Patel',
    status: 'rejected',
    createdAt: formatDate(8),
  },
];

export const mockStats: Stats = {
  totalCompanies: 127,
  newCompanies: 15,
  activeCompanies: 98,
  totalClients: 2543,
  newClients: 87,
  activeClients: 1842,
  pendingAnnouncements: 12,
};